# Generated by Django 4.1.7 on 2023-03-23 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quizStartDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
