# Generated by Django 4.1.7 on 2023-03-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_quizstartdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='questionRightAnswerId',
            field=models.IntegerField(default=0),
        ),
    ]
