# Generated by Django 4.1.7 on 2023-03-26 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quizEndDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
